/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#faf8ff',
        surface: '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'on-surface': '#131b2e',
        'on-surface-variant': '#3e4947',
        primary: '#005c55',
        'on-primary': '#ffffff',
        'primary-container': '#0f766e',
        'on-primary-container': '#a3faef',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        tertiary: '#6029c9',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7948e3',
        gold: '#005c55',
        positive: '#006c49',
        alert: '#ba1a1a',
        muted: '#6e7977',
        border: '#dae2fd',
        accent: '#C9A44C',
        success: '#3FA96A',
        negative: '#D9564B',
        'on-surface-muted': '#7C8797',
        'surface-elevated': '#161D2B',
        outline: '#232B3D',
        'accent-purple': '#8B7CF6',
        'accent-blue': '#5FA8D3',
      },
      fontFamily: {
        heading: ['Inter_500Medium'],
        'heading-semibold': ['Inter_600SemiBold'],
        'heading-bold': ['Inter_700Bold'],
        body: ['IBMPlexSans_400Regular'],
        'body-medium': ['IBMPlexSans_500Medium'],
        'body-semibold': ['IBMPlexSans_600SemiBold'],
        mono: ['IBMPlexMono_500Medium'],
        'mono-semibold': ['IBMPlexMono_600SemiBold'],
      },
    },
  },
  plugins: [],
};
