import { useNavigation, useRoute, RouteProp } from '@react-navigation/native';
import { ArrowDown, ArrowUp, ChevronLeft, Download, Share2, Sparkles, TrendingUp } from 'lucide-react-native';
import React from 'react';
import { Pressable, ScrollView, Share, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MoreStackParamList } from '../../navigation/types';
import { useBudgets, useTransactions } from '../../hooks';
import { formatCurrency } from '../../utils/formatCurrency';

type MonthlyReportRoute = RouteProp<MoreStackParamList, 'MonthlyReport'>;

const MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

function buildShareText(monthName: string, year: number, income: number, spent: number, saved: number) {
  return `FinSense AI Financial Summary — ${monthName} ${year}

Financial Health Score: 78 (Good)

Overview:
• Total Income: ${formatCurrency(income)}
• Spent: ${formatCurrency(spent)}
• Saved: ${formatCurrency(saved)}

✅ Your wins
• Reduced dining expenses by 12% compared to previous month.
• Met your monthly emergency fund contribution goal early.
• Credit score increased to 745 after debt repayment strategy.

⚠ Watch out for
• Subscription costs rose by ₹45 this month (3 new services).
• Utility bills are trending higher than the seasonal average.
• Upcoming car insurance renewal is higher than estimated.

AI Forecast: On track to increase net worth by ₹4,100 next month.

Generated by FinSense — Your AI Financial Assistant`;
}

export function MonthlyReportScreen() {
  const navigation = useNavigation();
  const route = useRoute<MonthlyReportRoute>();
  const monthIndex = route.params?.month ? MONTH_NAMES.indexOf(route.params.month) : new Date().getMonth();
  const year = route.params?.year ?? new Date().getFullYear();
  const monthName = MONTH_NAMES[monthIndex];

  const { data: transactions } = useTransactions();
  const { data: budgets } = useBudgets();

  const totalIncome = transactions?.filter((t) => t.amount > 0).reduce((s, t) => s + t.amount, 0) ?? 8450;
  const totalSpent = transactions?.filter((t) => t.amount < 0).reduce((s, t) => s + Math.abs(t.amount), 0) ?? 5230;
  const saved = totalIncome - totalSpent;

  const budgetItems = budgets?.slice(0, 4) ?? [
    { category: 'Housing', spent: 2092, limit: 2500 },
    { category: 'Invest', spent: 1307, limit: 1500 },
    { category: 'Food', spent: 1046, limit: 900 },
    { category: 'Others', spent: 785, limit: 600 },
  ];

  const totalBudget = budgetItems.reduce((s, b) => s + b.limit, 0);

  const handleShare = React.useCallback(() => {
    const text = buildShareText(monthName, year, totalIncome, totalSpent, saved);
    Share.share({ message: text, title: `FinSense Report — ${monthName} ${year}` });
  }, [monthName, year, totalIncome, totalSpent, saved]);

  return (
    <SafeAreaView edges={['top']} className="flex-1 bg-background">
      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 120 }} showsVerticalScrollIndicator={false}>
        {/* Top Bar */}
        <View className="flex-row items-center justify-between px-5 py-3">
          <Pressable onPress={() => navigation.goBack()} className="w-10 h-10 rounded-full bg-surface-container-low items-center justify-center">
            <ChevronLeft color="#151c27" size={20} />
          </Pressable>
          <View className="flex-row items-center gap-4">
            <Pressable onPress={handleShare}>
              <Share2 color="#3e4947" size={20} />
            </Pressable>
            <View className="w-10 h-10 rounded-full bg-surface-container-highest border-2 border-primary-fixed overflow-hidden items-center justify-center">
              <Text className="text-on-surface font-body-semibold text-sm">A</Text>
            </View>
          </View>
        </View>

        {/* Hero Section */}
        <View className="mx-5 rounded-3xl overflow-hidden bg-primary px-5 py-6 mb-5">
          <View className="items-center md:flex-row md:justify-between gap-4">
            <View className="items-center md:items-start gap-2">
              <Text className="text-on-primary font-body-medium text-xs opacity-80">AI FINANCIAL SUMMARY</Text>
              <Text className="text-on-primary font-heading-bold text-2xl">{monthName} {year} Report</Text>
              <View className="flex-row items-center gap-1.5 bg-on-primary/10 self-center md:self-start px-3 py-1 rounded-full mt-1">
                <TrendingUp color="#ffffff" size={14} />
                <Text className="text-on-primary font-body-medium text-xs">Good — up 5 points from Feb</Text>
              </View>
            </View>
            <View className="relative items-center justify-center">
              <View className="w-32 h-32 rounded-full border-4 border-on-primary/20 items-center justify-center">
                <View className="absolute inset-0 rounded-full border-4 border-on-primary border-t-transparent -rotate-45" />
                <View className="items-center">
                  <Text className="text-on-primary font-heading-bold text-[40px]">78</Text>
                  <Text className="text-on-primary font-body-medium text-[10px] uppercase tracking-wider opacity-80">Score</Text>
                </View>
              </View>
            </View>
            <View className="flex-row gap-3">
              <View className="bg-on-primary px-4 py-2 rounded-full flex-row items-center gap-2">
                <Download color="#005c55" size={16} />
                <Text className="text-primary font-body-semibold text-xs">Download</Text>
              </View>
              <Pressable onPress={handleShare} className="border border-on-primary px-4 py-2 rounded-full flex-row items-center gap-2">
                <Share2 color="#ffffff" size={16} />
                <Text className="text-on-primary font-body-semibold text-xs">Share</Text>
              </Pressable>
            </View>
          </View>
        </View>

        {/* Overview Section */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <Text className="text-on-surface font-heading-bold text-lg mb-4 flex-row items-center gap-2">📊 Overview</Text>
          <View className="gap-3">
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Total Income</Text>
                <Text className="text-on-surface font-heading-bold text-lg">{formatCurrency(totalIncome)}</Text>
              </View>
              <Text className="text-secondary text-3xl">💰</Text>
            </View>
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Spent</Text>
                <Text className="text-on-surface font-heading-bold text-lg">{formatCurrency(totalSpent)}</Text>
              </View>
              <Text className="text-alert text-3xl">🛒</Text>
            </View>
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Saved</Text>
                <Text className="text-primary font-heading-bold text-lg">{formatCurrency(saved)}</Text>
              </View>
              <Text className="text-primary text-3xl">🏦</Text>
            </View>
          </View>
        </View>

        {/* Donut Chart Section */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <Text className="text-on-surface font-heading-bold text-lg mb-4">Where your money went</Text>
          <View className="items-center md:flex-row justify-around gap-6">
            <View className="relative w-40 h-40 items-center justify-center">
              <View className="w-36 h-36 rounded-full border-[12px] border-surface-container-high items-center justify-center">
                <View className="absolute inset-0 rounded-full border-[12px] border-transparent"
                  style={{
                    borderTopColor: '#005c55',
                    borderRightColor: '#7948e3',
                    borderBottomColor: '#006c49',
                    borderLeftColor: '#ba1a1a',
                    transform: [{ rotate: '-45deg' }],
                  }}
                />
                <View className="items-center">
                  <Text className="text-on-surface-variant font-body text-xs">Total</Text>
                  <Text className="text-on-surface font-heading-bold text-lg">{formatCurrency(totalSpent)}</Text>
                </View>
              </View>
            </View>
            <View className="gap-2 w-full max-w-[160px]">
              {budgetItems.map((b, i) => {
                const colors = ['bg-primary', 'bg-tertiary-container', 'bg-secondary', 'bg-alert'];
                const pct = Math.round((b.spent / totalSpent) * 100);
                return (
                  <View key={b.category} className="flex-row items-center gap-2">
                    <View className={`w-3 h-3 rounded-full ${colors[i % colors.length]}`} />
                    <Text className="text-on-surface font-body text-sm">{b.category} ({pct}%)</Text>
                  </View>
                );
              })}
            </View>
          </View>
        </View>

        {/* Your Wins */}
        <View className="mx-5 bg-secondary-container/10 border border-secondary/20 rounded-2xl p-4 mb-4">
          <Text className="text-secondary font-heading-bold text-lg mb-3">✅ Your wins</Text>
          <View className="gap-3">
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-0.5">✓</Text>
              <Text className="text-on-surface font-body text-sm">Reduced dining expenses by <Text className="text-secondary font-heading-semibold">12%</Text> compared to February.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-0.5">✓</Text>
              <Text className="text-on-surface font-body text-sm">Met your monthly emergency fund contribution goal early.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-0.5">✓</Text>
              <Text className="text-on-surface font-body text-sm">Credit score increased to 745 after debt repayment strategy.</Text>
            </View>
          </View>
        </View>

        {/* Watch out for */}
        <View className="mx-5 bg-[#fffbeb] border border-amber-200 rounded-2xl p-4 mb-4">
          <Text className="text-amber-700 font-heading-bold text-lg mb-3">⚠️ Watch out for</Text>
          <View className="gap-3">
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-0.5">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Subscription costs rose by <Text className="text-amber-700 font-heading-semibold">₹45</Text> this month (3 new services).</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-0.5">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Utility bills are trending higher than the seasonal average.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-0.5">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Upcoming car insurance renewal is higher than estimated.</Text>
            </View>
          </View>
        </View>

        {/* Do this next */}
        <View className="mx-5 bg-tertiary/5 rounded-3xl p-5 mb-4 border border-tertiary/20">
          <View className="flex-row items-center gap-2 mb-4">
            <Sparkles color="#6029c9" size={18} />
            <Text className="text-tertiary font-heading-bold text-lg">Do this next</Text>
          </View>
          <View className="gap-3">
            {[
              { num: '1', title: 'Cancel inactive "Streamly"', desc: "You haven't used this subscription in 60 days. Saving: ₹14.99/mo." },
              { num: '2', title: 'Transfer ₹500 to ETF', desc: 'Your cash balance is high. Moving this will optimize interest gains.' },
              { num: '3', title: 'Set Budget: Groceries', desc: 'Limit to ₹600 to keep your savings rate at 35% next month.' },
            ].map((action) => (
              <View key={action.num} className="bg-surface p-4 rounded-2xl border border-tertiary/20">
                <View className="flex-row items-center gap-3 mb-2">
                  <View className="w-8 h-8 rounded-full bg-tertiary-container items-center justify-center">
                    <Text className="text-on-tertiary-container font-heading-bold text-sm">{action.num}</Text>
                  </View>
                  <Text className="text-on-surface font-heading-semibold text-base flex-1">{action.title}</Text>
                </View>
                <Text className="text-on-surface-variant font-body text-sm mb-3 ml-11">{action.desc}</Text>
                <Pressable className="bg-tertiary py-2.5 rounded-xl items-center ml-11 active:opacity-90">
                  <Text className="text-on-tertiary font-body-semibold text-sm">Do it</Text>
                </Pressable>
              </View>
            ))}
          </View>
        </View>

        {/* Next month forecast */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <View className="flex-row justify-between items-center mb-4">
            <Text className="text-on-surface font-heading-bold text-lg">Next month forecast</Text>
            <View className="flex-row gap-4">
              <View className="flex-row items-center gap-1.5">
                <View className="w-3 h-3 rounded-full bg-primary" />
                <Text className="text-on-surface-variant font-body text-[10px]">Income</Text>
              </View>
              <View className="flex-row items-center gap-1.5">
                <View className="w-3 h-3 rounded-full bg-alert" />
                <Text className="text-on-surface-variant font-body text-[10px]">Expense</Text>
              </View>
            </View>
          </View>
          <View className="h-48 bg-surface-container-lowest rounded-xl p-2 relative">
            <View className="flex-row items-end justify-between h-40 px-2">
              {[40, 30, 35, 20, 25, 15, 30].map((h, i) => (
                <View key={`bar-${i}`} className="flex-1 items-center mx-0.5">
                  <View
                    className="w-full h-[60%] rounded-t-sm border-t-2 border-primary"
                    style={{ backgroundColor: 'rgba(0,92,85,0.1)' }}
                  />
                  <View
                    className="w-full h-[40%] rounded-t-sm border-t-2 border-dashed border-alert mt-0.5"
                    style={{ backgroundColor: 'rgba(186,26,26,0.08)' }}
                  />
                </View>
              ))}
            </View>
            <View className="flex-row justify-between mt-2 px-2">
              {['Apr 01', 'Apr 10', 'Apr 20', 'Apr 30'].map((d) => (
                <Text key={`label-${d}`} className="text-on-surface-variant font-body text-[10px]">{d}</Text>
              ))}
            </View>
          </View>
          <View className="mt-3 bg-primary-container/10 p-3 rounded-xl flex-row gap-3 items-start">
            <Text className="text-primary text-lg">💡</Text>
            <Text className="text-on-surface font-body text-sm flex-1">
              AI Forecast: Based on your current trajectory, you are on track to increase your net worth by <Text className="font-heading-semibold">₹4,100</Text> in April.
            </Text>
          </View>
        </View>
      </ScrollView>

      {/* Bottom Share Button */}
      <View className="absolute bottom-6 left-5 right-5 items-center">
        <Pressable onPress={handleShare} className="bg-primary py-4 px-8 rounded-full shadow-lg flex-row items-center gap-2 w-full max-w-md justify-center">
          <Share2 color="#ffffff" size={18} />
          <Text className="text-on-primary font-heading-semibold text-base">Share report</Text>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}
