import { useNavigation } from '@react-navigation/native';
import { ChevronLeft, Download, Share2, Sparkles, TrendingUp } from 'lucide-react-native';
import React from 'react';
import { Pressable, ScrollView, Share, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const REPORT_TEXT = `FinSense AI Financial Summary — March 2026

Financial Health Score: 78 (Good — up 5 points from Feb)

Overview:
• Total Income: ₹8,450.00
• Spent: ₹5,230.00
• Saved: ₹3,220.00

Where your money went:
• Housing (40%)
• Investments (25%)
• Food (20%)
• Others (15%)

✅ Your wins
• Reduced dining expenses by 12% compared to February.
• Met your monthly emergency fund contribution goal early.
• Credit score increased to 745 after debt repayment strategy.

⚠ Watch out for
• Subscription costs rose by ₹45 this month (3 new services).
• Utility bills are trending higher than the seasonal average.
• Upcoming car insurance renewal is higher than estimated.

AI Forecast: On track to increase net worth by ₹4,100 in April.

Generated by FinSense — Your AI Financial Assistant`;

export function ReportsScreen() {
  const navigation = useNavigation();
  const handleShare = React.useCallback(() => {
    Share.share({ message: REPORT_TEXT, title: 'FinSense Financial Report' });
  }, []);

  return (
    <SafeAreaView edges={['top']} className="flex-1 bg-background">
      <ScrollView className="flex-1" contentContainerStyle={{ paddingBottom: 140 }} showsVerticalScrollIndicator={false}>
        {/* Top App Bar */}
        <View className="flex-row items-center justify-between px-5 py-3">
          <Pressable onPress={() => navigation.goBack()} className="flex-row items-center gap-2">
            <Text className="text-primary font-heading-bold text-lg">FinSense</Text>
          </Pressable>
          <View className="flex-row items-center gap-4">
            <Pressable onPress={handleShare}>
              <Share2 color="#3e4947" size={20} />
            </Pressable>
            <View className="w-10 h-10 rounded-full bg-surface-container-highest border-2 border-primary-fixed overflow-hidden items-center justify-center">
              <Text className="text-on-surface font-body-semibold text-sm">A</Text>
            </View>
          </View>
        </View>

        {/* Hero Section */}
        <View className="mx-5 rounded-3xl overflow-hidden bg-primary px-5 py-6 mb-5">
          <View className="items-center gap-3">
            <Text className="text-on-primary font-body-medium text-xs opacity-80">AI FINANCIAL SUMMARY</Text>
            <Text className="text-on-primary font-heading-bold text-2xl">March 2026 Report</Text>
            <View className="flex-row items-center gap-1.5 bg-on-primary/10 px-3 py-1 rounded-full">
              <TrendingUp color="#ffffff" size={14} />
              <Text className="text-on-primary font-body-medium text-xs">Good — up 5 points from Feb</Text>
            </View>
            <View className="relative items-center justify-center my-2">
              <View className="w-32 h-32 rounded-full border-4 border-on-primary/20 items-center justify-center">
                <View className="absolute inset-0 rounded-full border-4 border-on-primary border-t-transparent" style={{ transform: [{ rotate: '-45deg' }] }} />
                <View className="items-center">
                  <Text className="text-on-primary font-heading-bold text-[40px]">78</Text>
                  <Text className="text-on-primary font-body-medium text-[10px] uppercase tracking-wider opacity-80">Score</Text>
                </View>
              </View>
            </View>
            <View className="flex-row gap-3">
              <View className="bg-on-primary px-4 py-2 rounded-full flex-row items-center gap-2">
                <Download color="#005c55" size={16} />
                <Text className="text-primary font-body-semibold text-xs">Download</Text>
              </View>
              <Pressable onPress={handleShare} className="border border-on-primary px-4 py-2 rounded-full flex-row items-center gap-2">
                <Share2 color="#ffffff" size={16} />
                <Text className="text-on-primary font-body-semibold text-xs">Share</Text>
              </Pressable>
            </View>
          </View>
        </View>

        {/* Overview Section */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <View className="flex-row items-center gap-2 mb-4">
            <Text className="text-primary text-lg">📊</Text>
            <Text className="text-on-surface font-heading-bold text-lg">Overview</Text>
          </View>
          <View className="gap-3">
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Total Income</Text>
                <Text className="text-on-surface font-heading-bold text-lg">₹8,450.00</Text>
              </View>
              <Text className="text-secondary text-3xl">💰</Text>
            </View>
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Spent</Text>
                <Text className="text-on-surface font-heading-bold text-lg">₹5,230.00</Text>
              </View>
              <Text className="text-alert text-3xl">🛒</Text>
            </View>
            <View className="flex-row justify-between items-center bg-surface-container-low p-3 rounded-xl">
              <View>
                <Text className="text-on-surface-variant font-body text-xs">Saved</Text>
                <Text className="text-primary font-heading-bold text-lg">₹3,220.00</Text>
              </View>
              <Text className="text-primary text-3xl">🏦</Text>
            </View>
          </View>
        </View>

        {/* Donut Chart Section */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <Text className="text-on-surface font-heading-bold text-lg mb-4">Where your money went</Text>
          <View className="items-center gap-6">
            <View className="relative w-48 h-48 items-center justify-center">
              <View className="w-44 h-44 rounded-full border-[12px] border-surface-container-high items-center justify-center">
                <View
                  className="absolute inset-0 rounded-full border-[12px] border-transparent"
                  style={{
                    borderTopColor: '#005c55',
                    borderRightColor: '#7948e3',
                    borderBottomColor: '#006c49',
                    borderLeftColor: '#ba1a1a',
                    transform: [{ rotate: '-90deg' }],
                  }}
                />
                <View className="items-center">
                  <Text className="text-on-surface-variant font-body text-xs">Total</Text>
                  <Text className="text-on-surface font-heading-bold text-lg">₹5,230</Text>
                </View>
              </View>
            </View>
            <View className="flex-row flex-wrap gap-x-6 gap-y-2 max-w-xs">
              <View className="flex-row items-center gap-2">
                <View className="w-3 h-3 rounded-full bg-primary" />
                <Text className="text-on-surface font-body text-sm">Housing (40%)</Text>
              </View>
              <View className="flex-row items-center gap-2">
                <View className="w-3 h-3 rounded-full bg-tertiary-container" />
                <Text className="text-on-surface font-body text-sm">Invest (25%)</Text>
              </View>
              <View className="flex-row items-center gap-2">
                <View className="w-3 h-3 rounded-full bg-secondary" />
                <Text className="text-on-surface font-body text-sm">Food (20%)</Text>
              </View>
              <View className="flex-row items-center gap-2">
                <View className="w-3 h-3 rounded-full bg-alert" />
                <Text className="text-on-surface font-body text-sm">Others (15%)</Text>
              </View>
            </View>
          </View>
        </View>

        {/* Your Wins */}
        <View className="mx-5 bg-secondary-container/10 border border-secondary/20 rounded-2xl p-4 mb-4">
          <View className="flex-row items-center gap-2 mb-3">
            <Text className="text-secondary text-lg">✅</Text>
            <Text className="text-secondary font-heading-bold text-lg">Your wins</Text>
          </View>
          <View className="gap-3">
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-1">✓</Text>
              <Text className="text-on-surface font-body text-sm">Reduced dining expenses by <Text className="text-secondary font-heading-semibold">12%</Text> compared to February.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-1">✓</Text>
              <Text className="text-on-surface font-body text-sm">Met your monthly emergency fund contribution goal early.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-secondary mt-1">✓</Text>
              <Text className="text-on-surface font-body text-sm">Credit score increased to 745 after debt repayment strategy.</Text>
            </View>
          </View>
        </View>

        {/* Watch out for */}
        <View className="mx-5 bg-[#fffbeb] border border-amber-200 rounded-2xl p-4 mb-4">
          <View className="flex-row items-center gap-2 mb-3">
            <Text className="text-amber-700 text-lg">⚠️</Text>
            <Text className="text-amber-700 font-heading-bold text-lg">Watch out for</Text>
          </View>
          <View className="gap-3">
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-1">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Subscription costs rose by <Text className="text-amber-700 font-heading-semibold">₹45</Text> this month (3 new services).</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-1">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Utility bills are trending higher than the seasonal average.</Text>
            </View>
            <View className="flex-row items-start gap-3">
              <Text className="text-amber-600 mt-1">ℹ️</Text>
              <Text className="text-on-surface font-body text-sm">Upcoming car insurance renewal is higher than estimated.</Text>
            </View>
          </View>
        </View>

        {/* Do this next */}
        <View className="mx-5 bg-tertiary/5 rounded-3xl p-5 mb-4 border border-tertiary/20">
          <View className="flex-row items-center gap-2 mb-4">
            <Sparkles color="#6029c9" size={18} />
            <Text className="text-tertiary font-heading-bold text-lg">Do this next</Text>
          </View>
          <View className="gap-3">
            <View className="bg-surface p-4 rounded-2xl border border-tertiary/20">
              <View className="w-10 h-10 rounded-full bg-tertiary-container items-center justify-center mb-2">
                <Text className="text-on-tertiary-container font-heading-bold text-base">1</Text>
              </View>
              <Text className="text-on-surface font-heading-semibold text-lg mb-1">Cancel inactive "Streamly"</Text>
              <Text className="text-on-surface-variant font-body text-sm mb-3">You haven't used this subscription in 60 days. Saving: ₹14.99/mo.</Text>
              <Pressable className="bg-tertiary py-3 rounded-xl items-center active:opacity-90">
                <Text className="text-on-tertiary font-body-semibold text-sm">Do it</Text>
              </Pressable>
            </View>
            <View className="bg-surface p-4 rounded-2xl border border-tertiary/20">
              <View className="w-10 h-10 rounded-full bg-tertiary-container items-center justify-center mb-2">
                <Text className="text-on-tertiary-container font-heading-bold text-base">2</Text>
              </View>
              <Text className="text-on-surface font-heading-semibold text-lg mb-1">Transfer ₹500 to ETF</Text>
              <Text className="text-on-surface-variant font-body text-sm mb-3">Your cash balance is high. Moving this will optimize interest gains.</Text>
              <Pressable className="bg-tertiary py-3 rounded-xl items-center active:opacity-90">
                <Text className="text-on-tertiary font-body-semibold text-sm">Do it</Text>
              </Pressable>
            </View>
            <View className="bg-surface p-4 rounded-2xl border border-tertiary/20">
              <View className="w-10 h-10 rounded-full bg-tertiary-container items-center justify-center mb-2">
                <Text className="text-on-tertiary-container font-heading-bold text-base">3</Text>
              </View>
              <Text className="text-on-surface font-heading-semibold text-lg mb-1">Set Budget: Groceries</Text>
              <Text className="text-on-surface-variant font-body text-sm mb-3">Limit to ₹600 to keep your savings rate at 35% next month.</Text>
              <Pressable className="bg-tertiary py-3 rounded-xl items-center active:opacity-90">
                <Text className="text-on-tertiary font-body-semibold text-sm">Do it</Text>
              </Pressable>
            </View>
          </View>
        </View>

        {/* Next month forecast */}
        <View className="mx-5 bg-surface border border-outline-variant rounded-2xl p-4 mb-4">
          <View className="flex-row justify-between items-center mb-4">
            <Text className="text-on-surface font-heading-bold text-lg">Next month forecast</Text>
            <View className="flex-row gap-4">
              <View className="flex-row items-center gap-1.5">
                <View className="w-3 h-3 rounded-full bg-primary" />
                <Text className="text-on-surface-variant font-body text-[10px]">Projected Income</Text>
              </View>
              <View className="flex-row items-center gap-1.5">
                <View className="w-3 h-3 rounded-full bg-alert" />
                <Text className="text-on-surface-variant font-body text-[10px]">Estimated Expense</Text>
              </View>
            </View>
          </View>
          <View className="h-48 bg-surface-container-lowest rounded-xl p-2 relative">
            {/* Simplified chart bars */}
            <View className="flex-row items-end justify-between h-40 px-2">
              {[40, 30, 35, 20, 25, 15, 30].map((h, i) => (
                <View key={`bar-${i}`} className="flex-1 items-center mx-0.5">
                  <View
                    className="w-full rounded-t-sm border-t-2 border-primary"
                    style={{ height: `${h}%`, backgroundColor: 'rgba(0,92,85,0.1)' }}
                  />
                  <View
                    className="w-full rounded-t-sm border-t-2 border-dashed border-alert mt-0.5"
                    style={{ height: `${Math.max(h - 10, 5)}%`, backgroundColor: 'rgba(186,26,26,0.08)' }}
                  />
                </View>
              ))}
            </View>
            <View className="flex-row justify-between mt-2 px-2">
              {['Apr 01', 'Apr 10', 'Apr 20', 'Apr 30'].map((d) => (
                <Text key={`label-${d}`} className="text-on-surface-variant font-body text-[10px]">{d}</Text>
              ))}
            </View>
          </View>
          <View className="mt-3 bg-primary-container/10 p-3 rounded-xl flex-row gap-2 items-start">
            <Text className="text-primary text-lg">💡</Text>
            <Text className="text-on-surface font-body text-sm flex-1">
              AI Forecast: Based on your current trajectory, you are on track to increase your net worth by <Text className="font-heading-semibold">₹4,100</Text> in April.
            </Text>
          </View>
        </View>
      </ScrollView>

      {/* Bottom Action Buttons */}
      <View className="absolute bottom-8 left-5 right-5 items-center gap-3">
        <Pressable
          onPress={() => navigation.navigate('MonthlyReport' as never)}
          className="bg-tertiary py-4 px-8 rounded-full shadow-lg flex-row items-center gap-2 w-full max-w-md justify-center"
        >
          <Sparkles color="#ffffff" size={20} />
          <Text className="text-on-tertiary font-heading-semibold text-base">View Full Report</Text>
        </Pressable>
        <Pressable onPress={handleShare} className="bg-primary py-4 px-8 rounded-full shadow-lg flex-row items-center gap-2 w-full max-w-md justify-center">
          <Share2 color="#ffffff" size={20} />
          <Text className="text-on-primary font-heading-semibold text-base">Share report</Text>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}
